### ISSUE TITLE
[Enhancement] Support more file types

### ISSUE THREAD

**Issue by sparkmobi** [vicajilau/Drag-PDF#28]
hello

after testing your app I found that it only support images and pdf while other apps supports ppt,docx,xlsx

I have found this lib that you can use so you can support more file types ppt and docx
https://pub.dev/packages/libre_doc_converter
 excel sheets support I couldn't find it

**Comment by vicajilau** [comment]
First of all thank you for your interest and your proposal has been well received by the team to improve DragPDF. But unfortunately the dependency you mention is not supported. I share with you my research.

I tried to integrate it but my terminal just threw "Unsupported platform".

Unfortunately this dependency does not support android or iOS and requires a LibreOffice installation to run the dependency. The `toPdf()` function in its first line invokes the following function:

` final sofficePath = await getSofficePath();`

This triggers a mixin that behaves as above. I share with you a code capture that confirms this.
<img width="672" alt="image" src="https://github.com/vicajilau/Drag-PDF/assets/34163765/2b87453d-75a6-4ee0-8636-d9ba2c2938e9">

**Comment by vicajilau** [comment]
The proposal offered is not feasible to implement. Feel free to reopen this or another issue to discuss this or any other topic.
